routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Route::get('products','ProductController@index')->name('product.index');
//Route::get('products/create','ProductController@create')->name('product.create');
//Route::get('products/edit/{id}', 'ProductController@edit')->name('product.edit');
//Route::post('products/edit/{id}','ProductController@update');
//Route::post('products/create','ProductController@store');
//Route::delete('products/destroy/{id}', 'ProductController@destroy')->name('product.destroy');
//Route::get('products/show/{id}', 'ProductController@show')->name('product.show');


Route::resource('products', 'ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name', 'barcode', 'price', 'stock',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::all();
        return view('products.index', compact('products'));
    }

    public function create()
    {
        return view('products.create');
    }

    public function store(Request $request)
    {
        Product::create($request->all());
        return redirect()->route('products.index');
    }

    public function edit($id)
    {
        $product = Product::find($id);
        return view('products.edit', compact('product'));
    }

    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        $product->update($request->all());
        return redirect()->route('products.index');
    }

    public function destroy($id)
    {
        Product::find($id)->delete();
        return redirect()->route('products.index');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="فروشگاه استثنایی صادق">
    <meta name="author" content="sadegh">
    <title>فروشگاه استثنایی صادق</title>

    <!-- Bootstrap -->
    <link href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap-rtl/dist/css/bootstrap-rtl.min.css') }}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
@stack('header')
</head>
<body>
@yield('content')
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
@stack('footer')
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <form action="">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">افزودن محصول</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="name">نام محصول</label>
                                <input name="name" id="name" class="form-control" type="text">
                            </div>
                            <div class="form-group">
                                <label for="stock">موجودی انبار</label>
                                <input name="stock" id="stock" class="form-control" type="text">
                            </div>
                            <div class="form-group">
                                <label for="price">قیمت</label>
                                <input name="price" id="price" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="barcode">بارکد</label>
                                <input name="barcode" id="barcode" class="form-control" type="text">
                            </div>
                            <div class="form-group">
                                <label for="product_category_id">دسته بندی</label>
                                <input name="product_category_id" id="product_category_id" class="form-control" type="text">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <a href="{{ route('products.index') }}" type="submit" class="btn btn-primary">لفو</a>
                    <button type="submit" class="btn btn-primary">ثبت محصول</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <form action="" method="post">
            {{ csrf_field() }}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">افزودن محصول</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="name">نام محصول</label>
                                <input name="name" id="name" class="form-control" type="text" value="{{ $product->name }}">
                            </div>
                            <div class="form-group">
                                <label for="stock">موجودی انبار</label>
                                <input name="stock" id="stock" class="form-control" type="text" value="{{ $product->stock }}">
                            </div>
                            <div class="form-group">
                                <label for="price">قیمت</label>
                                <input name="price" id="price" class="form-control" type="text" value="{{ $product->price }}">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="barcode">بارکد</label>
                                <input name="barcode" id="barcode" class="form-control" type="text" value="{{ $product->barcode }}">
                            </div>
                            <div class="form-group">
                                <label for="product_category_id">دسته بندی</label>
                                <input name="product_category_id" id="product_category_id" class="form-control" type="text" value="{{ $product->product_category_id }}">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <a href="{{ route('product.index') }}" type="submit" class="btn btn-primary">لفو</a>
                    <button type="submit" class="btn btn-primary">ثبت محصول</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
    <h2>لیست محصولات</h2>
    <a href="{{ route('products.create') }}"><h5>افزودن محصول</h5></a>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>نام محصول</th>
            <th>موجودی انبار</th>
            <th>قیمت</th>
            <th>بارکد</th>
            <th>دسته بندی</th>
            <th>عملیات</th>
        </tr>
        </thead>
        <tbody>
        @foreach($products as $product)
            <tr>
                <td>{{ $product->name }}</td>
                <td>{{ $product->stock }}</td>
                <td>{{ $product->price }}</td>
                <td>{{ $product->barcode }}</td>
                <td>Halo badan</td>
                <td>
                    <a href="{{ route('products.edit', $product->id) }}" class="btn btn-warning btn-xs" title="ویرایش">
                        <i class="glyphicon glyphicon-edit"></i>
                    </a>
                    <form style="display: inline" action="{{ route('products.destroy', $product->id) }}" method="post">
                        {!! csrf_field() !!}
                        <input type="hidden" name="_method" value="DELETE">
                        <button onclick="return confirm('are u sure?')" type="submit" class="btn btn-danger btn-xs" title="حذف">
                            <i class="glyphicon glyphicon-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection